version: '2'

services:
    jenkins-master:
        build: jenkins-master
        environment:
            - CASC_JENKINS_CONFIG=/var/casc_configs
        volumes:
            - jenkins-home:/var/jenkins_home
            - jenkins-log:/var/log/jenkins
            - /var/run/docker.sock:/var/run/docker.sock
            - ./casc_configs/master:/var/casc_configs
        ports:
            - "8080:8080"

volumes:
  jenkins-home:
  jenkins-log:
